### ISSUE TITLE
blocks.STONE etc seem to error

### ISSUE THREAD

**Issue by admiyo** [r1chardj0n3s/pycode-minecraft#1]
I was able to move a hand with hand.forward()  etc, but any of the commands which place a block seem to fail:

the simplest test is hand.put(blocks.STONE)  will not only be not-executed, but a chat("done") placed after it in the book is also not executed.  It feels like a  case of needing 

import blocks

at the top of a python file.

Running the pre-built binaries and forge 10.2

**Comment by r1chardj0n3s** [comment]
Thanks Adam! There's something about how the mod is built for distribution that seems to be disabling reflection into the blocks class (which doesn't need to be imported), which prevents access to the attributes from jython. I'll have to look into it!

**Comment by r1chardj0n3s** [comment]
The names are no longer de-obfuscated when running against Minecraft For Real (as opposed to the Forge-modified version I've been developing against). Makes sense, of course, but does mean I need a slight change of plans with the API. Actually, it'll end up being simpler, which is good :-)

Fix will be released as 1.3, very soon indeed.

**Comment by r1chardj0n3s** [comment]
I've released 1.3 which has the fix for this issue.

**Comment by admiyo** [comment]
Tested.  No Change.  Confirmed that the Jython does not pass beyond the put call.
hand.put(block.STONE) or variations still do not execute.  Running with  pycode-1.3.jar

**Comment by r1chardj0n3s** [comment]
Hey Adam. Please have another look at the docs. The usage has now changed, so that call is "hand.put('stone')"

**Comment by admiyo** [comment]
Yep, that works!  Thanks.

**Comment by r1chardj0n3s** [comment]
Awesome!!
